# Application
quarkus.http.port=8080

# PostgreSQL datasource
quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=sms_user
quarkus.datasource.password=sms_password
quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5433/sms_platform

# Hibernate ORM
quarkus.hibernate-orm.database.generation=update
quarkus.hibernate-orm.log.sql=true

# Kafka
kafka.bootstrap.servers=localhost:9092

mp.messaging.outgoing.message-processing.connector=smallrye-kafka
mp.messaging.outgoing.message-processing.topic=sms-message-processing
mp.messaging.outgoing.message-processing.value.serializer=io.quarkus.kafka.client.serialization.ObjectMapperSerializer

mp.messaging.incoming.message-processing-in.connector=smallrye-kafka
mp.messaging.incoming.message-processing-in.topic=sms-message-processing
mp.messaging.incoming.message-processing-in.value.deserializer=com.smsplatform.service.MessageProcessingEventDeserializer
mp.messaging.incoming.message-processing-in.group.id=sms-platform

# Swagger UI
quarkus.swagger-ui.always-include=true