# Application
quarkus.http.port=8080

# PostgreSQL datasource
quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=sms_user
quarkus.datasource.password=sms_password
quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5433/sms_platform

# Hibernate ORM
quarkus.hibernate-orm.database.generation=update
quarkus.hibernate-orm.log.sql=true

# Swagger UI
quarkus.swagger-ui.always-include=true